// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WP_Liga.Migrations
{
    [DbContext(typeof(SLContext))]
    partial class SLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Godiste")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TimID")
                        .HasColumnType("int");

                    b.Property<int>("Visina")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TimID");

                    b.ToTable("Igrac");
                });

            modelBuilder.Entity("Models.Liga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Liga");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LigaID")
                        .HasColumnType("int");

                    b.Property<string>("Skor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LigaID");

                    b.ToTable("Tim");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Rezultat1")
                        .HasColumnType("int");

                    b.Property<int>("Rezultat2")
                        .HasColumnType("int");

                    b.Property<int?>("Tim1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Tim2ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Tim1ID");

                    b.HasIndex("Tim2ID");

                    b.ToTable("Utakmica");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.HasOne("Models.Tim", "Tim")
                        .WithMany("Igraci")
                        .HasForeignKey("TimID");

                    b.Navigation("Tim");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.HasOne("Models.Liga", "Liga")
                        .WithMany("Timovi")
                        .HasForeignKey("LigaID");

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("Models.Utakmica", b =>
                {
                    b.HasOne("Models.Tim", "Tim1")
                        .WithMany()
                        .HasForeignKey("Tim1ID");

                    b.HasOne("Models.Tim", "Tim2")
                        .WithMany("Utakmice")
                        .HasForeignKey("Tim2ID");

                    b.Navigation("Tim1");

                    b.Navigation("Tim2");
                });

            modelBuilder.Entity("Models.Liga", b =>
                {
                    b.Navigation("Timovi");
                });

            modelBuilder.Entity("Models.Tim", b =>
                {
                    b.Navigation("Igraci");

                    b.Navigation("Utakmice");
                });
#pragma warning restore 612, 618
        }
    }
}
